fix: correct gridelements early access compatibility
* fix: fatal error due to incompatible declaration of sortRecordsIntoMatrix()

Fatal error: Declaration of ITplusX\HeadlessGridelements\DataProcessing\GridChildrenProcessor::sortRecordsIntoMatrix() must be compatible with GridElementsTeam\Gridelements\DataProcessing\GridChildrenProcessor::sortRecordsIntoMatrix(): array in /var/www/private/typo3conf/ext/headless_gridelements/Classes/DataProcessing/GridChildrenProcessor.php on line 16

* style: applied psr-12

* fix: php warning for element-less column

PHP Warning: Undefined array key 102 in /var/www/private/typo3conf/ext/headless_gridelements/Classes/DataProcessing/GridChildrenProcessor.php line 36

* Use empty instead of isset