fix: fatal error due to incompatible declaration of sortRecordsIntoMatrix()
Fatal error: Declaration of ITplusX\HeadlessGridelements\DataProcessing\GridChildrenProcessor::sortRecordsIntoMatrix() must be compatible with GridElementsTeam\Gridelements\DataProcessing\GridChildrenProcessor::sortRecordsIntoMatrix(): array in /var/www/private/typo3conf/ext/headless_gridelements/Classes/DataProcessing/GridChildrenProcessor.php on line 16